spring:
  application:
    name: Expense Tracker
  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=true;trustServerCertificate=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        jdbc:
          time_zone: UTC
logging:
  console:
    enabled: true
  file:
    enabled: true
    name: logs/expense-tracker.log
  level:
    root: INFO
    com.ksportfolio.expensetracker: DEBUG
  logback:
    rollingpolicy:
      file-name-pattern: logs/expense-tracker-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 30